version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: testing_application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn TestingApplication.wsgi:application --bind localhost–º:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: