# Generated by Django 5.1 on 2024-08-26 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('size_of_answers', models.IntegerField(default=4, verbose_name='Количество показываемых вариантов')),
                ('answer_options', models.ManyToManyField(blank=True, null=True, related_name='answer_option', to='TestApp.answer', verbose_name='варианты ответа')),
                ('right_answers', models.ManyToManyField(blank=True, null=True, related_name='right_answers', to='TestApp.answer', verbose_name='правильные ответы')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('size_of_pages', models.IntegerField(default=20, verbose_name='Количество вопросов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('questions', models.ManyToManyField(to='TestApp.question', verbose_name='Вопросы теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestPass',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id для составного ключа')),
                ('result_ball', models.FloatField(verbose_name='Оценка')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TestApp.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прохождение теста пользователем',
                'verbose_name_plural': 'История прохождений пользователями',
            },
        ),
    ]
