# Generated by Django 5.1 on 2024-08-31 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpass',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 18, 50, 12, 561125), verbose_name='Дата выполнения теста'),
        ),
    ]
