# Generated by Django 5.1 on 2024-08-31 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_testpass_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpass',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 18, 52, 55, 891108), verbose_name='Дата выполнения теста'),
        ),
        migrations.AlterField(
            model_name='testpass',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
